config/routes.rb
Rails.application.routes.draw do
  get 'positions/new'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy, :excel_to_db]
  resources :relationships, only: [:create, :destroy]

  root 'static_pages#home'

  match '/signup', to:'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_post_form.html.erb
<% if @current_user.creator?%>
<div class="postform">
    <h6>Загрузка файла .xlsx, .xls или .ods</h6>
    
    <%= form_for @post, html: { multipart: true } do |f| %>
    
        <%= render 'shared/error_messages', object: f.object %>
    
        <div class="field">
    
            <div class="form-group">
            <%= f.file_field :attachment, id:"exampleInputFile" %>
            </div>
            <%= f.text_area :content, placeholder: "Коментарий не более 50 символов" %>
        </div>
  
        <%= f.submit "Отправить", class: "btn btn-default" %>
    
    <% end %>
</div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
<% unless @user.creator? %>
  <a href="<%= following_user_path(@user) %>">
    Подписан на:
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
<% else %>    
  </a>
  <a href="<%= followers_user_path(@user) %>">
    Подписчики:
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
<% end %>  
  </a>
</div>