config/routes.rb
Rails.application.routes.draw do
  get 'positions/new'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy, :excel_to_db]
  resources :relationships, only: [:create, :destroy]

  root 'static_pages#home'

  match '/signup', to:'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
        <%= link_to "", root_path, class: "brand" %>
      <nav>
        <ul class="nav pull-right">
              
          <% unless signed_in? %>
              <li><%= link_to "Регистрация", signup_path %></li>
              <li><%= link_to "Войти", signin_path %></li>
          <% else %>
              <% if @current_user.creator?%><li><%= link_to "Создать запись", current_user %></li><% end %>
              <li><%= link_to "Компании", users_path %></li>
              <li><%= link_to "Выйти", signout_path, method: "delete" %></li>
          <%end%>
        </ul>
      </nav>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Мрц</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
    <%= render 'layouts/header' %>
    
    <div class="container" style="padding-top:60px;">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>    
    	<%= yield %>
    </div>
      <%= debug(params) if Rails.env.development? %>
    
</body>
</html>